#!/usr/bin/env bash
# Update package list and install Nginx
sudo apt update
sudo apt install -y nginx

# Create a backup of the default Nginx configuration file
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

# Create an HTML file with "Hello World!" content
echo "Hello World!" | sudo tee /var/www/html/index.html

# Configure Nginx to redirect /redirect_me
echo "server {
    listen 80;
    listen [::]:80 default_server;
    root   /var/www/html/index.html;
    index  index.html;
    location /redirect_me {
        return 301 https://twitter.com/Emmanue17280546;
    }
}" > sudo tee /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
sudo service nginx restart
