#!/usr/bin/env bash
# Update package list and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Ensure Nginx is running
sudo service nginx start

# Create a backup of the default Nginx configuration file
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

# Create an HTML file with "Hello World!" content
echo "Hello World!" | sudo tee /var/www/html/index.html

# Configure Nginx to redirect /redirect_me
sudo sed -i '/location \/ {/i     location /redirect_me {\n        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n        }' /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
sudo service nginx restart
