#!/usr/bin/env bash
# Update package list and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Ensure Nginx is running
sudo service nginx start

# Create a backup of the default Nginx configuration file
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

# Create an HTML file with "Hello World!" content
echo "Hello World!" | sudo tee /var/www/html/index.html

# Create an 404 HTML code file with "Ceci n'est pas une page" content
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Configure Nginx to redirect /redirect_me
sudo sed -i '/location \/ {/i error_page 404 /404.html;\n    location = /404.html {\n        root /var/www/html;\n        internal;\n    }\n' /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
sudo service nginx restart
