#!/usr/bin/env bash

# Update and install Nginx
sudo apt update
sudo apt install -y nginx

# Fetch the hostname of the server
HOSTNAME=$(hostname)

# Create an HTML file with "Hello World!" content
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Hello World!" | sudo tee /etc/nginx/html/index.html

# Create an 404 HTML code file with "Ceci n'est pas une page" content
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
echo "Ceci n'est pas une page" | sudo tee /etc/nginx/html/404.html

# Configure Nginx to redirect /redirect_me
sudo sed -i '/location \/ {/i error_page 404 /404.html;\n    location = /404.html {\n        root /var/www/html;\n        internal;\n    }\n' /etc/nginx/sites-available/default

# Insert the add_header directive into the default server block
sudo sed -i "/server_name _;/a \\    add_header X-Served-By '$HOSTNAME';" /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service restart nginx

# Ensure Nginx starts on boot
sudo service enable nginx

# Enable UFW firewall
sudo ufw enable

# Allow SSH traffic
sudo ufw allow ssh

# Allow HTTP and HTTPS traffic for Nginx
sudo ufw allow 'Nginx Full'

# Reload UFW to apply the changes
sudo ufw reload