#!/usr/bin/env bash

# Update and install Nginx
sudo apt update
sudo apt install -y nginx

# Fetch the hostname of the server
HOSTNAME=$(hostname)

# Create an HTML file with "Hello World!" content
echo "Hello World!" | sudo tee /var/www/html/index.html

# Create an 404 HTML code file with "Ceci n'est pas une page" content
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Configure Nginx to redirect /redirect_me
sudo sed -i '/location \/ {/i     location /redirect_me {\n        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n        }' /etc/nginx/sites-available/default

# Insert the add_header directive into the default server block
sudo sed -i "/server_name _;/a \\    add_header X-Served-By '$HOSTNAME';" /etc/nginx/sites-available/default

# Ensure Nginx starts on boot
sudo systemctl enable nginx

# Restart Nginx
sudo systemctl restart nginx
