#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

# Update and install HAProxy
sudo apt update
sudo apt install -y nginx
sudo apt install -y haproxy

# Backup the default HAProxy configuration
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

# Get the hostname of the load balancer
HOSTNAME=$(hostname)

# Create an HTML file with "Hello World!" content
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Hello World!" | sudo tee /etc/nginx/html/index.html

# Create an 404 HTML code file with "Ceci n'est pas une page" content
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
echo "Ceci n'est pas une page" | sudo tee /etc/nginx/html/404.html

# Configure Nginx to redirect /redirect_me
sudo sed -i '/location \/ {/i error_page 404 /404.html;\n    location = /404.html {\n        root /var/www/html;\n        internal;\n    }\n' /etc/nginx/sites-available/default

# Insert the add_header directive into the default server block
sudo sed -i "/server_name _;/a \\    add_header X-Served-By '$HOSTNAME';" /etc/nginx/sites-available/default

# Write a new HAProxy configuration
sudo bash -c 'cat > /etc/haproxy/haproxy.cfg << EOF
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web01 513210-web-01:80 check
    server web02 513210-web-02:80 check

listen stats
    bind *:8080
    stats enable
    stats uri /stats
    stats hide-version
    stats auth admin:password
EOF'

# Restart Nginx to apply changes
sudo service restart nginx

# Ensure Nginx starts on boot
sudo service enable nginx

# Restart HAProxy to apply the new configuration
sudo service restart haproxy

# Enable HAProxy to start on boot
sudo service enable haproxy
