#!/usr/bin/env bash
# Displays a list of currently running processes.a: Show processes for all users, u: Display detailed information about each process, x: Include processes without a controlling terminal.
ps -a -x -u -f
