#!/usr/bin/env bash
# Function to update /etc/hosts file
update_hosts_file() {
    sudo sed -i "/$1/c\\$2" /etc/hosts
}

# Update localhost to resolve to 127.0.0.2
update_hosts_file "localhost" "127.0.0.2 localhost"

# Update facebook.com to resolve to 8.8.8.8
update_hosts_file "facebook.com" "8.8.8.8 facebook.com"
